### ISSUE TITLE
mistake in bayes theory

### ISSUE THREAD

**Issue by kayschulz** [learn-co-curriculum/dsc-2-21-12-PE-MAP#1]

**Comment by kayschulz** [comment]
<img width="1440" alt="Screen Shot 2019-05-01 at 8 30 01 AM" src="https://user-images.githubusercontent.com/45648843/57025239-6eaf9c80-6beb-11e9-89e6-fe2ca93b6f85.png">
the numerator should be P(X given theta) * P(theta)
the denominator should be P(X)

**Comment by LoreDirick** [comment]
fixed now, thanks @kayschulz !
